### ISSUE TITLE
What should be changed to support newer versions of pyodide ?

### ISSUE THREAD

**Issue by matt-grain** [xhluca/material-ui-in-pyodide#1]
Bonjour et joyeuses fêtes!

This template is so interesting (even more with the pythonify version). but I tried to make it run with newer version of pyodide (0.19+) and I have this error I don't understand:

````python
react-dom.production.min.js:141 
        
Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function App at 0x9bed80>"
    at _getPtr (pyodide.asm.js:10:115582)
    at pyodide.asm.js:10:124133
    at Object.get (pyodide.asm.js:10:124405)
    at vb (react-dom.production.min.js:70:294)
    at Pj (react-dom.production.min.js:231:157)
    at di (react-dom.production.min.js:168:305)
    at Nj (react-dom.production.min.js:168:236)
    at sc (react-dom.production.min.js:168:96)
    at gf (react-dom.production.min.js:162:109)
    at Pa (react-dom.production.min.js:157:184)
Ye @ react-dom.production.min.js:141
pyodide.asm.js:10 
        
       Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 26, in <module>
pyodide.JsException: Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function App at 0x9bed80>"

    at new_error (pyodide.asm.js:10:218123)
    at pyodide.asm.wasm:0xdef7c
    at pyodide.asm.wasm:0xdf077
    at Module._pythonexc2js (pyodide.asm.js:10:900301)
    at Module.callPyObjectKwargs (pyodide.asm.js:10:119233)
    at Module.callPyObject (pyodide.asm.js:10:119442)
    at PyProxyClass.apply (pyodide.asm.js:10:126886)
    at Object.apply (pyodide.asm.js:10:125914)
    at Object.runPython (pyodide.asm.js:10:149946)
    at main (react.html:24:21)
````

`Try using create_proxy`.... Any idea what should me changed?

Thanks!

**Comment by matt-grain** [comment]
Ah... this article helped :)
https://jeff.glass/post/pyscript-why-create-proxy/

````python
import js
from pyodide.ffi import create_proxy

e = js.React.createElement

def App(props, children):
    return e(
        'div', None,
        e('h1', None, 'Hello World'),
        e('p', None, 'This is my first React app.'),
    )

# Create a div to contain our component
dom_container = js.document.createElement('div')
js.document.body.appendChild(dom_container)

js.ReactDOM.render(e(create_proxy(App), None), dom_container)
````

**Comment by matt-grain** [comment]
Any idea on how to modify your `pythonify` function to support `create_proxy`?

````python
def pythonify(component):
    """
    Makes a react component feel like you are calling a function
    """

    def aux(self, old_args, old_kwargs, *args, **kwargs):
        kwargs = {__to_camel_case(k): v for k, v in kwargs.items()}
        if old_args is None:
            old_args = []
        if old_kwargs is None:
            old_kwargs = {}

        old_args.extend(args)
        old_kwargs.update(kwargs)

        args = old_args
        kwargs = old_kwargs

        rc = js.React.createElement(component, jsobj(**kwargs), *args)
        rc.update = partial(aux.__get__(rc, rc.__class__), args, kwargs)

        return rc

    return partial(aux, component, None, None)
````

**Comment by matt-grain** [comment]
Ah I think I found one working version :)

````python
def pythonify(component):
    """
    Makes a react component feel like you are calling a function
    """

    def aux(self, old_args, old_kwargs, *args, **kwargs):
        kwargs = {__to_camel_case(k): v for k, v in kwargs.items()}
        if old_args is None:
            old_args = []
        if old_kwargs is None:
            old_kwargs = {}

        old_args.extend(args)
        old_kwargs.update(kwargs)

        args = old_args
        kwargs = old_kwargs

        if callable(component) and not isinstance(component, JsProxy):
            print(f"Create proxy for {component.__name__}")
            rc = js.React.createElement(create_proxy(component), jsobj(**kwargs), *args)
        else:
            rc = js.React.createElement(component, jsobj(**kwargs), *args)
        
        rc.update = partial(aux.__get__(rc, rc.__class__), args, kwargs)

        return rc

    return partial(aux, component, None, None)
````

**Comment by matt-grain** [comment]
Better but I still have a problem with:

````python
@mui.makeStyles
def use_styles(theme):
    return jsobj(
        root=jsobj(margin=theme.spacing(6, 0, 3)),
        light_bulb=jsobj(verticalAlign="middle", marginRight=theme.spacing(1)),
    )
````

**Comment by matt-grain** [comment]
Ah, got something :)

````python
def use_styles(theme):
    obj = jsobj(
        root=jsobj(margin=theme.spacing(6, 0, 3)),
        light_bulb=jsobj(verticalAlign="middle", marginRight=theme.spacing(1)),
    )
    mui_use_styles = mui.makeStyles(obj)
    return mui_use_styles()
````
